### ISSUE TITLE
Mac Os or Linux installation ? 

### ISSUE THREAD

**Issue by felipeinfantino** [admin-shell-io/aasx-package-explorer#390]
Can this be installed on Mac Os Mojave or on any Linux distro?

If so, could you please provide installation steps?

**Comment by aorzelskiGH** [comment]
Please take a look on the newest activities of AASX Package Explorer with .NET Blazor:
https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2021-08-17

**Comment by nrasulnrasul** [comment]
I tried the BlazorUI on Ubuntu 20.04 and I had the following problem when I tried to start the BlazorUI. I had the donet version 3.1.412.

https://github.com/admin-shell-io/aasx-package-explorer/releases/download/v2021-08-17.alpha/BlazorUI.2021-08-17.alpha.zip
```

~/sandbox/aas/BlazorUI $ dotnet BlazorUI.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/shaik/sandbox/aas/BlazorUI/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, specify the appropriate framework in /home/shaik/sandbox/aas/BlazorUI/BlazorUI.runtimeconfig.json.
```
```
~/sandbox/aas/BlazorUI $ dotnet --version
3.1.412
```
Do I need to install any other dependencies to run the BlazorUI on Ubuntu 20.04?

**Comment by aorzelskiGH** [comment]
Yes, please install ASP.NET Core 3.1 before: https://dotnet.microsoft.com/download/dotnet/3.1

**Comment by aorzelskiGH** [comment]
You may now also simply try first
https://github.com/admin-shell-io/aasx-package-explorer/releases
admin-shell-io.com:5005

**Comment by wieland-s** [comment]
same problem as @nrasulnrasul on mac under macOS BigSur. 

```
> dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.400
 Commit:    d61950f9bf

Laufzeitumgebung:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

`libgdiplus` ist also installed as described [here](https://docs.microsoft.com/en-us/dotnet/core/install/macos#libgdiplus)

**Comment by kgarrels** [comment]
This is what worked for me:
- download BlazorUI.2021-08-17.alpha.zip
- unzip unsing `unzip BlazorUI.2021-08-17.alpha.zip´. The macOS Archive Utility does not repsect the directory structure.
- replace content of BlazorUI.runtimeconfig.json with this:
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "5.0.9"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "5.0.9"
      }
    ],
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```

- run it using `dotnet BlazorUI.dll'

```
kai@iMac/~/Downloads/BlazorUI > dotnet --version
5.0.400
kai@iMac/~/Downloads/BlazorUI > dotnet --info
.NET SDK (gemäß "global.json"):
 Version:   5.0.400
 Commit:    d61950f9bf

Laufzeitumgebung:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  5.0.101 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
kai@iMac/~/Downloads/BlazorUI > locate libh
kai@iMac/~/Downloads/BlazorUI >  locate libhostpolicy.dylib
/Applications/Microsoft Excel.app/Contents/SharedSupport/Microsoft.Mashup.Container.app/Contents/SharedSupport/libhostpolicy.dylib
/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.0.0/libhostpolicy.dylib
/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.1/libhostpolicy.dylib
/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.9/libhostpolicy.dylib
kai@iMac/~/Downloads/BlazorUI > dotnet BlazorUI.dll
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/kai/Downloads/BlazorUI
```

**Comment by wieland-s** [comment]
@kgarrels solution work for me! Thank you very much. 

One more problem I had to deal with was the following: 
First I tried it exactly like kgarrels wrote within a clean directory. It started now, but: 
```
[...]
      https://localhost:5001/_framework/blazor.server.js:1:46522
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at BlazorInputFile.InputFile.OnAfterRenderAsync(Boolean firstRender)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'f--ZESDizLkwM8IM4X3C_WQ5J0scOcJDEPrKsGaY8g8'.
      Microsoft.JSInterop.JSException: Could not find 'BlazorInputFile.init' ('BlazorInputFile' was undefined).
```  
Ok, then I tried it with the "old" directory from yesterday: It works! 🎉 

The difference: I used macOS Archive Utility to unzip. As kgarrels described this does not respect the directory structure. Not known that `unzip` will a different behavior I fixed it manually with a bash script. After some research I noticed: It is a **permission problem**. Using `unzip` on command line results in: 
```
>  ls -la BlazorUI/wwwroot/_content/BlazorInputFile/
ls: BlazorUI/wwwroot/_content/BlazorInputFile/: Permission denied
``` 

Changing the permissions in Finder fixed it. 

----- 
@nrasulnrasul can you report the same about the zipping? 
@kgarrels you did not had a permission problem?

**Comment by kgarrels** [comment]
Glad it works for you as well.

I did not have a permission problem.

**Comment by nrasulnrasul** [comment]
@wieland-s  Sorry for late reply.  I still have problems in running it on Ubuntu 20.04

```
~/sandbox/aas/BlazorUI $ dotnet BlazorUI.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/shaik/sandbox/aas/BlazorUI/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/home/shaik/sandbox/aas/BlazorUI/BlazorUI.runtimeconfig.json' did not specify a framework.
  - If this should be a framework-dependent app, specify the appropriate framework in '/home/shaik/sandbox/aas/BlazorUI/BlazorUI.runtimeconfig.json'.
```
I installed ASP.NET Core 3.1 using  

> sudo apt-get install -y aspnetcore-runtime-3.1

And updated content of BlazorUI.runtimeconfig.json as below 
```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "5.0.10"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "5.0.10"
      }
    ],
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```


```
~/sandbox/aas/BlazorUI $ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.401
 Commit:    4bef5f3dbf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.401/

Host (useful for support):
  Version: 5.0.10
  Commit:  e1825b4928

.NET SDKs installed:
  3.1.412 [/usr/share/dotnet/sdk]
  5.0.401 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.19 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by aorzelskiGH** [comment]
I think that I could fix the bug. For .NET core also --runtime win-x64 was set incorrect before.

Please try the ZIP https://github.com/admin-shell-io/aasx-package-explorer/suites/4014919363/artifacts/101394018
which belongs to the current build https://github.com/admin-shell-io/aasx-package-explorer/runs/3855862902

**Comment by OParczyk** [comment]
So I've managed to run the BlazorUI version on Ubuntu 20.04 by doing the following:
Install the dotnet 5.0 SDK following [these steps](https://docs.microsoft.com/de-de/dotnet/core/install/linux-ubuntu#2004-).
Install the ASPNetCore 3.1 runtime with `sudo apt install aspnetcore-runtime-3.1`.
Download the zip from [this comment](https://github.com/admin-shell-io/aasx-package-explorer/issues/390#issuecomment-939806323).
Unzip using `unzip aasx-package-explorer-blazorui.zip` as per [this comment](https://github.com/admin-shell-io/aasx-package-explorer/issues/390#issuecomment-915884340). This is neccessary because the paths inside the zip use backslashes.
Correct the permissions using `chmod -R 775 BlazorUI`.
Enter the directory (`cd BlazorUI`)
Finally execute using with `dotnet BlazorUI.dll`

Viewing the sample AAS using your server instances works. However:
Creating a new AASX seems impossible.
As noted previously one cannot "Upload" own AASX to be viewed, as the button stays disabled even after selecting `*` and saving.
the LICENCE-Link doesn't work, as it references `LICENSE.TXT`, yet only `LICENSE.txt` is present. This is only a small oversight, but maybe other problems stem from similar sources.

Since I could not create a new AAS I've tried the following to run the 'real' AASX Package Explorer:
Download [this artifact zip](https://github.com/admin-shell-io/aasx-package-explorer/suites/4014919363/artifacts/101394019) linked by [this comment](https://github.com/admin-shell-io/aasx-package-explorer/issues/390#issuecomment-939806323)
Extract the inner .zip
Unzip the extracted .zip using `unzip aasx-package-explorer.zip`
Correct the permissions using `chmod -R 775 BlazorUI`.
Trying to execute by entering the directory and running `dotnet AasxPackageExplorer.exe` yielded the same error BlazorUI did before the introduction of the runtimeconfig.json.
Copy the `BlazorUI.runtimeconfig.json` into the directory containing the package explorer and rename to `AasxPackageExplorer.runtimeconfig.json`
At this point executing `dotnet AasxPackageExplorer.exe` yields the following:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Abgebrochen
```
I've tried various version numbers in the json but nothing changed.

I certainly believe it to be in your interest for this implementation to be cross-plattform, too. How can I, how can we get there?

**Comment by aorzelskiGH** [comment]
I am happy that you found a way to run BlazorUI on Ubuntu. Creating a new AAS is so far not implemented in the BlazorUI mockup.

AasxPackageExplorer.exe is a .NET framework WPF application. Unfortunately it is not possible to run this on Linux. This is why we started the blazorUI variant.

Would you be interested to join our activities and to further develop blazorUI to make it usable?

**Comment by aorzelskiGH** [comment]
I am happy, that this still works somehow. We only continue to compile it and do not further develop it at the moment.
Be aware that the web version is not fully implemented yet. Especially dialogs may not work.
I think I had this problem already in the past. It seems that inputfile.js of blazorinputfile is missing:
https://github.com/SteveSandersonMS/BlazorInputFile/tree/master/BlazorInputFile/wwwroot 
Please copy this into wwwroot/wwwroot\_content\BlazorInputFile
Please try

**Comment by HansG89** [comment]
In my case the file you mentioned is already there: `wwwroot/_content/BlazorInputFile/inputfile.js`
It got also loaded by the browser. I can see the source in Chromes developer tools. But it seems that no action is triggered when selecting the "*" from the dropdown.

**Comment by aorzelskiGH** [comment]
Please contact me by my email (see license.txt or about). We need to schedule a short meeting next week. Then will look together.

Von: Tobias Gruner ***@***.***>
Gesendet: Dienstag, 25. Januar 2022 14:03
An: admin-shell-io/aasx-package-explorer ***@***.***>
Cc: Andreas Orzelski ***@***.***>; Mention ***@***.***>
Betreff: Re: [admin-shell-io/aasx-package-explorer] Mac Os or Linux installation ? (#390)

***External email! Do not click links or open attachments unless you recognize the sender and know the content is safe.***

In my case the file you mentioned is already there: wwwroot/_content/BlazorInputFile/inputfile.js
It got also loaded by the browser. I can see the source in Chromes developer tools. But it seems that no action is triggered when selecting the "*" from the dropdown.

-
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadmin-shell-io%2Faasx-package-explorer%2Fissues%2F390%23issuecomment-1021161401&data=04%7C01%7C%7C0132b9b806eb49bd2b9f08d9e003023e%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637787125808965163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PVq7O0PrqIFwxtk6PvPFpQcKeaMdsr54LAYZT7pjREE%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALVQLABA3WIVWEKOWL34RGDUX2NQBANCNFSM47ADLPHA&data=04%7C01%7C%7C0132b9b806eb49bd2b9f08d9e003023e%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637787125808965163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aMXF89GI%2BlcEuqO%2FuSPGNGcGq3pbpO6dMkWy488G%2Bus%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0132b9b806eb49bd2b9f08d9e003023e%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637787125808965163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7Ak4H6AUxrKeto%2BDc4cx03VfNlu3ftgqCjZ8SDL7Bpk%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0132b9b806eb49bd2b9f08d9e003023e%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637787125808965163%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8vBuRBlz3kq2cT2E6a%2By%2FVUz1YJ%2B%2Boh6WAmIETnhXdA%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>


..................................................................
Phoenix Contact GmbH & Co. KG

Sitz der Gesellschaft / registered office of the company: 32825 Blomberg
USt-Id-Nr.: DE124613250
Pers. haftende Gesellschafterin / personally liable partner: Phoenix Contact Verwaltungs GmbH
Amtsgericht Lemgo HRB 5273 / district court Lemgo HRB 5273
Kom. Ges. Amtsgericht Lemgo HRA 3746 / limited commercial partnership district court Lemgo HRA 3746 
Geschäftsführer / Executive Board: Frank Stührenberg (Vorsitzender / Chief Executive Officer), Dirk Görlitzer, Torsten Janwlecke, Ulrich Leidecker, Frank Possel-Dölken, Axel Wachholz 
___________________________________________________________________
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren, jegliche anderweitige Verwendung sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
----------------------------------------------------------------------------------------------------
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure, distribution or other use of the material or parts thereof is strictly forbidden.
___________________________________________________________________

**Comment by HansG89** [comment]
I sent you an email to the mentioned address. No response yet

**Comment by aorzelskiGH** [comment]
***@***.***

Von: Tobias Gruner ***@***.***>
Gesendet: Donnerstag, 27. Januar 2022 08:16
An: admin-shell-io/aasx-package-explorer ***@***.***>
Cc: Andreas Orzelski ***@***.***>; Mention ***@***.***>
Betreff: Re: [admin-shell-io/aasx-package-explorer] Mac Os or Linux installation ? (#390)

***External email! Do not click links or open attachments unless you recognize the sender and know the content is safe.***

I sent you an email to the mentioned address. No response yet

-
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadmin-shell-io%2Faasx-package-explorer%2Fissues%2F390%23issuecomment-1022914151&data=04%7C01%7C%7Cdd6a383eca93411a6faf08d9e164e003%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637788645639245195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FJrpD8c2M5ReKcDge9Ic3G9vjV4kF7%2BD3%2Br9%2Bi%2FikHQ%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALVQLAGZDN4N7OOFJ2DLEW3UYDWLDANCNFSM47ADLPHA&data=04%7C01%7C%7Cdd6a383eca93411a6faf08d9e164e003%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637788645639245195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h6dvddEtSjy2%2BavfINcbHu4y7ytMJQVGZPzfYAlFfj0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cdd6a383eca93411a6faf08d9e164e003%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637788645639245195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v0X1H22ZWFxVyhwD3w3VMUcaNZwYxQcd8GRgHKHoQ7A%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cdd6a383eca93411a6faf08d9e164e003%7C6868843bf0124c95a18ebab826cca9ac%7C0%7C0%7C637788645639245195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PZrN%2BIWwdiBFbdURnHfrTz%2FPVnUi7SWOZkj08Yzeup4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


..................................................................
Phoenix Contact GmbH & Co. KG

Sitz der Gesellschaft / registered office of the company: 32825 Blomberg
USt-Id-Nr.: DE124613250
Pers. haftende Gesellschafterin / personally liable partner: Phoenix Contact Verwaltungs GmbH
Amtsgericht Lemgo HRB 5273 / district court Lemgo HRB 5273
Kom. Ges. Amtsgericht Lemgo HRA 3746 / limited commercial partnership district court Lemgo HRA 3746 
Geschäftsführer / Executive Board: Frank Stührenberg (Vorsitzender / Chief Executive Officer), Dirk Görlitzer, Torsten Janwlecke, Ulrich Leidecker, Frank Possel-Dölken, Axel Wachholz 
___________________________________________________________________
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren, jegliche anderweitige Verwendung sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.
----------------------------------------------------------------------------------------------------
This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure, distribution or other use of the material or parts thereof is strictly forbidden.
___________________________________________________________________

**Comment by atextor** [comment]
Hi,
I tried getting either AASX Package Explorer or Blazor Explorer running using the tips in this thread on Linux, but I could not make it work. Here is what I tried:
* Downloaded BlazorExplorer.zip (current latest release, 2023-09-12.alpha)
* Installed the Dotnet runtime from Microsoft. `dotnet --list-runtimes` contains Microsoft.AspNetCore.App and Microsoft.NETCore.App in multiple versions (3.1.32, 6.0.22 and 7.0.11)
* Found out it's not called BlazorUI any more (as mentioned in previous posts in this thread) but BlazorExplorer instead
* Fixed permissions (`chmod -R a+X BlazorExplorer`)
* BlazorExplorer.runtimeconfig.json contains an entry for `Microsoft.WindowsDesktop.App`, which is not supported on Linux. I'd assume this entry is not needed, BlazorExplorer is a headless application, isn't it? I removed the entry from the file.
* Start the application with `dotnet BlazorExplorer.dll`
* It starts successfully, telling me:
  ```
  info: Microsoft.Hosting.Lifetime[14]
        Now listening on: http://localhost:5000
  info: Microsoft.Hosting.Lifetime[14]
        Now listening on: https://localhost:5001
  info: Microsoft.Hosting.Lifetime[0]
        Application started. Press Ctrl+C to shut down.
  info: Microsoft.Hosting.Lifetime[0]
        Hosting environment: Production
  ```
* Upon opening localhost:5000 in the browser, the app crashes.
  <details>
    <summary>Error message and stack trace shown by the app</summary>
    warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Could not load file or assembly 'PresentationCore, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
      
     System.IO.FileNotFoundException: Could not load file or assembly 'PresentationCore, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
      
      File name: 'PresentationCore, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
         at BlazorUI.AasxMenuBlazor.LoadAndRender
         at BlazorUI.Data.BlazorSession..ctor() in D:\a\aasx-package-explorer\aasx-package-explorer\src\BlazorExplorer\Data\BlazorSession.cs:line 221
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

      fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '4DEg3800V8dKxliV6k9SWnZrovlqP8RTyHOEz3Hh-dc'.
      System.IO.FileNotFoundException: Could not load file or assembly 'PresentationCore, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
      
      File name: 'PresentationCore, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
         at BlazorUI.AasxMenuBlazor.LoadAndRender
         at BlazorUI.Data.BlazorSession..ctor() in D:\a\aasx-package-explorer\aasx-package-explorer\src\BlazorExplorer\Data\BlazorSession.cs:line 221
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
         at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
  </details>

As you can see, it contains a similar error message to the one mentioned in [this comment](https://github.com/admin-shell-io/aasx-package-explorer/issues/390#issuecomment-964221275), but this time it's not from running the AASX Package Explorer, but Blazor explorer.

(The web UI remains blank and displays only the message: An error has occurred. This application may no longer respond until reloaded.)
